---
title: "Séries bonbons"
output: pdf_document
date: "2023-04-27"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
require(zoo)
require(tseries)
library(readr)
library(tidyverse)
library(pander)
require(fUnitRoots)
require (forecast)
```

```{r}
datafile <- "valeurs_mensuelles.csv"
data <- read.csv(datafile, sep =";")

data <- data %>% 
  filter(!row_number() %in% c(1, 2, 3))%>%
  select(1,2)

colnames(data)[1] = "dates"
colnames(data)[2] = "prod"

data <- apply(data, 2, rev)
data <- as.data.frame (data)

data$prod <- as.numeric (data$prod)


dates_char <- as.character(data$dates)
dates_char[1];dates_char[length(dates_char)]
dates <- as.yearmon(seq(from=1990+1/12,to=2008+1/12,by=1/12))

prod <- zoo(data$prod,order.by=dates)

```

```{r}
plot(cbind(prod))
```
```{r}
acf(prod)
```
--> pic en 1 : intuition pas stationnaire

```{r}
summary(lm(prod ~ dates))
```
```{r}
help ("adfTest")
```

```{r}
adf <- adfTest (prod, lag=0, type = "ct")
```


```{r}
Qtests <- function(series, k, fitdf=0) {
  pvals <- apply(matrix(1:k), 1, FUN=function(l) {
    pval <- if (l<=fitdf) NA else Box.test(series, lag=l, type="Ljung-Box", fitdf=fitdf)$p.value
    return(c("lag"=l,"pval"=pval))
  })
  return(t(pvals))
}

Qtests(adf@test$lm$residuals, 24, fitdf = length(adf@test$lm$coefficients))
```

```{r}
adfTest_valid <- function(series, kmax, type){
  k <- 0
  noautocorr <- 0
  while (noautocorr==0){
    cat(paste0("ADF with ",k," lags: residuals OK? "))
    adf <- adfTest(series, lags=k, type=type)
    pvals <- Qtests(adf@test$lm$residuals, 24, fitdf = length(adf@test$lm$coefficients))[,2]
    if (sum(pvals<0.05,na.rm=T)==0) {
      noautocorr <- 1; cat("OK \n")}
    else cat("nope \n")
    k <- k+1
  }
  return(adf)
}

adf <- adfTest_valid(prod,24,type="ct")
Qtests(adf@test$lm$residuals, 24, fitdf = length(adf@test$lm$coefficients))
adf
```

```{r}
dprod <- diff(prod,1)
plot(cbind(dprod))
```
```{r}
lt <- lm(dprod ~ dates[-1])
summary(lt)
```

```{r}
adf <- adfTest_valid(dprod,24,type="nc")
adf
```
## Partie 2

```{r}
x <- dprod
par(mfrow=c(1,2))
acf(x);pacf(x)
Acf(x);Pacf(x)
```

```{r}
signif <- function(estim){
  coef <- estim$coef
  se <- sqrt(diag(estim$var.coef))
  t <- coef/se
  pval <- (1-pnorm(abs(t)))*2
  return(rbind(coef,se,pval))
}

modelchoice <- function(p,q,data=x, k=24){
  estim <- try(arima(data, c(p,1,q),optim.control=list(maxit=20000)))
  if (class(estim)=="try-error") return(c("p"=p,"q"=q,"arsignif"=NA,"masignif"=NA,"resnocorr"=NA, "ok"=NA))
  arsignif <- if (p==0) NA else signif(estim)[3,p]<=0.05
  masignif <- if (q==0) NA else signif(estim)[3,p+q]<=0.05
  resnocorr <- sum(Qtests(estim$residuals,24,length(estim$coef)-1)[,2]<=0.05,na.rm=T)==0
  checks <- c(arsignif,masignif,resnocorr)
  ok <- as.numeric(sum(checks,na.rm=T)==(3-sum(is.na(checks))))
  return(c("p"=p,"q"=q,"arsignif"=arsignif,"masignif"=masignif,"resnocorr"=resnocorr,"ok"=ok))
}
## fonction pour estimer et v´erifier tous les arima(p,q) avec p<=pmax et q<=max
armamodelchoice <- function(pmax,qmax) {
  pqs <- expand.grid(0:pmax,0:qmax) 
  t(apply(matrix(1:dim(pqs)[1]),1,function(row) {
    p <- pqs[row,1]; q <- pqs[row,2]
    cat(paste0("Computing ARMA(",p,",",q,") \n"))
    modelchoice(p,q)
  }))
}

pmax = 9
qmax = 8

armamodels <- armamodelchoice(pmax,qmax) #estime tous les arima (patienter...)
selec <- armamodels[armamodels[,"ok"]==1&!is.na(armamodels[,"ok"]),] #modèles bien ajustés et valides
selec
```

```{r}
pqs <- apply(selec,1,function(row) list("p"=as.numeric(row[1]),"q"=as.numeric(row[2])))
names(pqs) <- paste0("arma(",selec[,1],",",selec[,2],")")
models <- lapply(pqs,function(pq) arima(x,c(pq[["p"]],0,pq[["q"]])))
vapply(models, FUN.VALUE=numeric(2), function(m) c("AIC"=AIC(m),"BIC"=BIC(m)))

AIC
```

-> ARMA (1,1), ARIMA (1,1,1)
